[Feature][CI] Add Dead Link Checker
apache/dolphinscheduler pull request #10000
Opened 2022-05-11 14:08 UTC by wuchunfu

## Purpose of the pull request
close #9999

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2022-05-11 16:18 UTC, davidzollo approved these changes
LGTM

2022-05-12 09:22 UTC, dailidong commented
Please handle the dead link pngs

2022-05-12 09:22 UTC, dailidong requested changes, later dismissed
Please handle the dead link pngs

2022-05-12 14:21 UTC, wuchunfu commented
> Please handle the dead link pngs

I don't know what those two pngs are, can anyone help me?

2022-05-15 12:52 UTC, zhongjiajie commented
But we already have the dead link checker in our docs.yaml https://github.com/apache/dolphinscheduler/blob/dev/.github/workflows/docs.yml#L48-L60 what the difference is? and could we combine them?

2022-05-15 14:02 UTC, wuchunfu commented
> But we already have the dead link checker in our docs.yaml https://github.com/apache/dolphinscheduler/blob/dev/.github/workflows/docs.yml#L48-L60 what the difference is? and could we combine them?

Well, close it if you don't need my contribution this time.

2022-05-16 02:04 UTC, zhongjiajie commented on .github/workflows/dead-link-checker.yaml
> +    - cron: '0 18 * * *'  # TimeZone: UTC 0
Hi @wuchunfu , maybe we should add this setting or others setting we miss into `docs.yaml` CI configuration. WDYT

2022-05-16 09:57 UTC, wuchunfu commented on .github/workflows/dead-link-checker.yaml
> +    - cron: '0 18 * * *'  # TimeZone: UTC 0
Thanks jiajie for the review, I'll finish it

2022-05-18 10:35 UTC, zhongjiajie reviewed
LGTM, thanks~

2022-05-18 10:35 UTC, zhongjiajie approved these changes

2022-05-18 10:36 UTC, zhongjiajie commented
I rerun the failed CI

2022-05-19 08:48 UTC, zhongjiajie commented
Restarted it again

2022-05-21 02:38 UTC, kezhenxu94 approved these changes

2022-05-21 02:41 UTC, merged

2022-06-17 03:06 UTC, devosend commented
This pr should be cherry-pick to milestone 3.0.0-beta-2? @zhongjiajie @wuchunfu

2022-06-17 03:26 UTC, kezhenxu94 commented
> This pr should be cherry-pick to milestone 3.0.0-beta-2? @zhongjiajie @wuchunfu

This is just CI settings, not functionality related, I think we don't need to back port this to previous version.

2022-06-17 03:55 UTC, devosend commented
> > This pr should be cherry-pick to milestone 3.0.0-beta-2? @zhongjiajie @wuchunfu
> 
> This is just CI settings, not functionality related, I think we don't need to back port this to previous version.

But is will affect cherry-pick of #10325

2022-06-17 04:48 UTC, kezhenxu94 commented
> > > This pr should be cherry-pick to milestone 3.0.0-beta-2? @zhongjiajie @wuchunfu
> > 
> > 
> > This is just CI settings, not functionality related, I think we don't need to back port this to previous version.
> 
> But is will affect cherry-pick of #10325

OK if that's the case, you can cherry pick this. It's not functionality related so you can choose to or not to cherry pick it, if other depends on this you can do it

2022-06-17 05:37 UTC, zhongjiajie commented
> > > > This pr should be cherry-pick to milestone 3.0.0-beta-2? @zhongjiajie @wuchunfu
> > > 
> > > 
> > > This is just CI settings, not functionality related, I think we don't need to back port this to previous version.
> > 
> > 
> > But is will affect cherry-pick of #10325
> 
> OK if that's the case, you can cherry pick this. It's not functionality related so you can choose to or not to cherry pick it, if other depends on this you can do it

Agrees with that we can or can not cherry pick this to nest release branch