[Fix-11197] [Master] Dependency detection bug
apache/dolphinscheduler pull request #11204
Opened 2022-07-29 08:46 UTC by JinyLeeChina

closed by #11197

2022-08-12 02:20 UTC, caishunfeng commented on dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
> +        ProcessInstance runningProcess = processService.findLastRunningProcess(definitionCode, dateInterval.getStartTime(), dateInterval.getEndTime());
related pr: https://github.com/apache/dolphinscheduler/pull/11424

2022-08-23 04:04 UTC, caishunfeng commented on dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/TaskInstanceMapper.xml
> +    <select id="queryLastTaskInstanceList" resultType="org.apache.dolphinscheduler.dao.entity.TaskInstance">
```suggestion
    <select id="queryTaskInstanceListByTime" resultType="org.apache.dolphinscheduler.dao.entity.TaskInstance">
```

2022-08-23 04:04 UTC, caishunfeng commented on dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
> +    private DependResult dependResultByProcessInstance(ProcessInstance processInstance, DateInterval dateInterval) {
Please add some comments.

2022-08-23 04:04 UTC, caishunfeng commented on dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
> +                Map<Long, String> definiteTask = taskDefinitionLogs.stream().filter(log -> !log.getTaskType().equals(TaskConstants.TASK_TYPE_SUB_PROCESS)
Why filter these logic tasks?

2022-08-23 04:04 UTC, caishunfeng commented on dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
> +                    }
What is the point of this part?

2022-08-23 04:14 UTC, lenboo requested changes

2022-08-23 04:14 UTC, lenboo commented on dolphinscheduler-master/src/main/java/org/apache/dolphinscheduler/server/master/utils/DependentExecute.java
> +            List<ProcessTaskRelation> taskRelations = processService.findRelationByCode(processInstance.getProcessDefinitionCode(),
The workflow dependent only need check the process instance state.
There are scenarios in which only some tasks are run, resulting in a successful workflow.

2022-09-20 03:12 UTC, lordk911 commented
Any new development?

2022-09-22 01:52 UTC, lordk911 commented
@SbloodyS Why this PR hung up such a long time, I think dep bug is important to be repair. or there is any other PR to resolve this problem? thanks.

2022-10-14 03:55 UTC, JinyLeeChina commented
refer #12219,  I think it need new pr to solve, someone want to contribute ?

2022-10-17 09:57 UTC, lordk911 commented
> refer #12219, I think it need new pr to solve, someone want to contribute ?

#12219 has no code changed but only doc , anything more need to do for is PR?

2023-02-01 08:55 UTC, closed without merging