[BUG][BE-12113]fix htrace dependency conflicts
apache/dolphinscheduler pull request #12126
Opened 2022-09-23 11:50 UTC by Tianqi-Dotes

## Purpose of the pull request

fix htrace dependency conflicts
![8a7bc93cdba0ee455fad3de0dc45932](https://user-images.githubusercontent.com/36755957/191954062-daf8edfd-efa7-4ece-80e5-bc8431249371.jpg)

## Brief change log

fix htrace dependency conflicts

## Verify this pull request

Manually verified the change by testing locally.
If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2022-09-24 14:19 UTC, caishunfeng commented
@Tianqi-Dotes please check the dependency license.

2022-09-24 14:38 UTC, kezhenxu94 requested changes
Please replace all htrace-core with hbase-noop-htrace. We don't need tracing and the htrace has CVEs.

2022-09-24 14:38 UTC, kezhenxu94 commented on dolphinscheduler-api/pom.xml
> +        <dependency>
Please replace this with 

```xml
             <dependency>
                 <groupId>org.apache.hbase.thirdparty</groupId>
                 <artifactId>hbase-noop-htrace</artifactId>
             </dependency>
```

2022-09-24 14:38 UTC, kezhenxu94 commented on dolphinscheduler-api/pom.xml
> +        <dependency>
This should be removed.

2022-09-25 14:52 UTC, caishunfeng commented on pom.xml
> +        <htrace.version>4.2.0-incubating</htrace.version>
Should manage in bom.

2022-09-25 15:25 UTC, caishunfeng commented
related pr: #11881

2022-09-25 17:20 UTC, kezhenxu94 requested changes

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-api/pom.xml
> +            <scope>runtime</scope>
These are unnecessary. Please remove

```suggestion
```

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-common/pom.xml
> +            <version>${htrace.version}</version>
Same here

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
> +            <version>${htrace.version}</version>
Here

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
> +                </exclusion>
These are unnecessary

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
> +            <version>${htrace.version}</version>
Remove

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
> +                <exclusion>
Remove

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-master/pom.xml
> +            <version>${htrace.version}</version>
Remove

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-master/pom.xml
> +                <exclusion>
Remove

2022-09-25 17:20 UTC, kezhenxu94 commented on dolphinscheduler-server/pom.xml
> +            <version>${htrace.version}</version>
Remove

2022-09-25 17:20 UTC, kezhenxu94 commented on pom.xml
> +        <htrace.version>4.1.1</htrace.version>
Remove this

2022-09-26 02:57 UTC, Tianqi-Dotes commented on dolphinscheduler-api/pom.xml
> +        <dependency>
done

2022-09-26 02:57 UTC, Tianqi-Dotes commented on dolphinscheduler-api/pom.xml
> +        <dependency>
done

2022-09-26 02:57 UTC, Tianqi-Dotes commented on pom.xml
> +        <htrace.version>4.2.0-incubating</htrace.version>
done

2022-09-26 02:58 UTC, Tianqi-Dotes commented on dolphinscheduler-api/pom.xml
> +            <scope>runtime</scope>
done

2022-09-26 02:58 UTC, Tianqi-Dotes commented on dolphinscheduler-common/pom.xml
> +            <version>${htrace.version}</version>
done

2022-09-26 02:59 UTC, Tianqi-Dotes commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
> +            <version>${htrace.version}</version>
done

2022-09-26 03:01 UTC, Tianqi-Dotes commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-api/pom.xml
> +                </exclusion>
done

2022-09-26 03:01 UTC, Tianqi-Dotes commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
> +            <version>${htrace.version}</version>
done

2022-09-26 03:03 UTC, Tianqi-Dotes commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-hive/pom.xml
> +                <exclusion>
done

2022-09-26 03:03 UTC, Tianqi-Dotes commented on dolphinscheduler-master/pom.xml
> +            <version>${htrace.version}</version>
done

2022-09-26 03:03 UTC, Tianqi-Dotes commented on dolphinscheduler-server/pom.xml
> +            <version>${htrace.version}</version>
done

2022-09-26 03:03 UTC, Tianqi-Dotes commented on pom.xml
> +        <htrace.version>4.1.1</htrace.version>
done

2022-09-26 04:03 UTC, kezhenxu94 approved these changes

2022-09-26 05:49 UTC, merged

2022-09-26 05:50 UTC, caishunfeng commented
Thanks~