[Feature][Api] Refactor api.controller.EnvironmentController
apache/dolphinscheduler pull request #12158
Opened 2022-09-27 02:53 UTC by tracehh

fix: #12075 

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2022-09-29 03:13 UTC, davidzollo submitted a review, later dismissed
LGTM

2022-10-14 02:05 UTC, ruanwenjun requested changes

2022-10-14 02:05 UTC, ruanwenjun commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/EnvironmentService.java
> +    Result queryEnvironmentByCode(Long code);
```suggestion
    Environment queryEnvironmentByCode(Long code);
```

Please remove the Result in service.

2022-10-14 02:05 UTC, ruanwenjun commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/EnvironmentServiceImpl.java
> +        if (checkResult.getCode() != Status.SUCCESS.getCode()) {
We can directly throw ServiceException in service, use Result is not convenient.

2022-10-28 08:33 UTC, closed without merging