fix #13837 the Invalid log : worker worker have not received the hear…
apache/dolphinscheduler pull request #13838
Opened 2023-03-30 16:56 UTC by lxorc

fix #13837 the Invalid log : worker worker have not received the hearbet

2023-03-31 02:00 UTC, ruanwenjun commented
We don't need to add this check, this case might be due to we registering an empty node?

2023-03-31 02:44 UTC, lxorc commented
> We don't need to add this check, this case might be due to we registering an empty node? Could you please describe how to reproduce this.

Yes, by default a `worker` node will be loaded in `registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); `

```java
registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); 
String[] parts = path.split("/");  // REGISTRY_DOLPHINSCHEDULER_WORKERS = /nodes/worker
final String workerAddress = parts[parts.length - 1];  // workerAddress  = worker
syncSingleWorkerNodeInfo(workerAddress, JSONUtils.parseObject(data, WorkerHeartBeat.class));
workerNodeInfo.put(workerAddress, info);  // put "worker" key into the workerNodeInfo
` ` `

2023-03-31 03:45 UTC, ruanwenjun commented
> > We don't need to add this check, this case might be due to we registering an empty node? Could you please describe how to reproduce this.
> 
> Yes, by default a `worker` node will be loaded in `registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); `
> 
> ```java
> registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); 
> String[] parts = path.split("/");  // REGISTRY_DOLPHINSCHEDULER_WORKERS = /nodes/worker
> final String workerAddress = parts[parts.length - 1];  // workerAddress  = worker
> if (type == Type.UPDATE) // the Type.UPDATE is  Node /nodes/worker update ,   case NODE_UPDATED: type(Type.UPDATE);
> syncSingleWorkerNodeInfo(workerAddress, JSONUtils.parseObject(data, WorkerHeartBeat.class));  //  ???
> workerNodeInfo.put(workerAddress, info);  // put "worker" key into the workerNodeInfo
> ```
> 
> The effect is that the `addr` of `getHostWeight` will be the `worker` and `heartBeat == null`.
> 
> so
> 
> ```java
>         if (heartBeat == null) {
>             logger.warn("worker {} in work group {} have not received the heartbeat", addr, workerGroup);
>             return Optional.empty();
>         }
> ```

So we only need to subscribe the child path of REGISTRY_DOLPHINSCHEDULER_WORKERS

2023-03-31 05:44 UTC, lxorc commented
> > > We don't need to add this check, this case might be due to we registering an empty node? Could you please describe how to reproduce this.
> > 
> > 
> > Yes, by default a `worker` node will be loaded in `registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); `
> > ```java
> > registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); 
> > String[] parts = path.split("/");  // REGISTRY_DOLPHINSCHEDULER_WORKERS = /nodes/worker
> > final String workerAddress = parts[parts.length - 1];  // workerAddress  = worker
> > if (type == Type.UPDATE) // the Type.UPDATE is  Node /nodes/worker update ,   case NODE_UPDATED: type(Type.UPDATE);
> > syncSingleWorkerNodeInfo(workerAddress, JSONUtils.parseObject(data, WorkerHeartBeat.class));  //  ???
> > workerNodeInfo.put(workerAddress, info);  // put "worker" key into the workerNodeInfo
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The effect is that the `addr` of `getHostWeight` will be the `worker` and `heartBeat == null`.
> > so
> > ```java
> >         if (heartBeat == null) {
> >             logger.warn("worker {} in work group {} have not received the heartbeat", addr, workerGroup);
> >             return Optional.empty();
> >         }
> > ```
> 
> So we only need to subscribe the event of REGISTRY_DOLPHINSCHEDULER_WORKERS's child path

Please help to review my code to see if there are other problems. If there is a better implementation, please reply to me.

2023-04-01 02:49 UTC, ruanwenjun commented
> > > > We don't need to add this check, this case might be due to we registering an empty node? Could you please describe how to reproduce this.
> > > 
> > > 
> > > Yes, by default a `worker` node will be loaded in `registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); `
> > > ```java
> > > registryClient.subscribe(REGISTRY_DOLPHINSCHEDULER_WORKERS, new WorkerDataListener()); 
> > > String[] parts = path.split("/");  // REGISTRY_DOLPHINSCHEDULER_WORKERS = /nodes/worker
> > > final String workerAddress = parts[parts.length - 1];  // workerAddress  = worker
> > > if (type == Type.UPDATE) // the Type.UPDATE is  Node /nodes/worker update ,   case NODE_UPDATED: type(Type.UPDATE);
> > > syncSingleWorkerNodeInfo(workerAddress, JSONUtils.parseObject(data, WorkerHeartBeat.class));  //  ???
> > > workerNodeInfo.put(workerAddress, info);  // put "worker" key into the workerNodeInfo
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The effect is that the `addr` of `getHostWeight` will be the `worker` and `heartBeat == null`.
> > > so
> > > ```java
> > >         if (heartBeat == null) {
> > >             logger.warn("worker {} in work group {} have not received the heartbeat", addr, workerGroup);
> > >             return Optional.empty();
> > >         }
> > > ```
> > 
> > 
> > So we only need to subscribe the event of REGISTRY_DOLPHINSCHEDULER_WORKERS's child path
> 
> Please help to review my code to see if there are other problems. If there is a better implementation, please reply to me. And I have fixed it in my production environment and it works fine.

Does master path will have this problem? could you please change the master together?

2023-07-04 04:01 UTC, ruanwenjun commented
Please fix the code style by `mvn spotless:apply`

2023-08-29 07:34 UTC, Gallardot requested changes

2023-08-29 07:34 UTC, Gallardot commented on dolphinscheduler-registry/dolphinscheduler-registry-api/src/main/java/org/apache/dolphinscheduler/registry/api/RegistryClient.java
> +        return path != null && path.startsWith(Constants.REGISTRY_DOLPHINSCHEDULER_WORKERS) && !path.equals(Constants.REGISTRY_DOLPHINSCHEDULER_WORKERS);
```suggestion
        return path != null && path.startsWith(Constants.REGISTRY_DOLPHINSCHEDULER_WORKERS)
                && !path.equals(Constants.REGISTRY_DOLPHINSCHEDULER_WORKERS);
```


@lxorc Do you have time to work on this PR? Maybe I can help with that. We also encountered this issue, and I have tested this PR in our environment. It is feasible.

2024-01-21 00:23 UTC, closed without merging