Update ZeppelinTask.java
apache/dolphinscheduler pull request #13861
Opened 2023-04-03 10:48 UTC by xiaomin0322

add login method

## Purpose of the pull request

add login zeppelin method

## Brief change log

org.apache.dolphinscheduler.plugin.task.zeppelin.ZeppelinTask
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2023-04-04 02:29 UTC, EricGao888 requested changes
Where do u plan to configure the zeppelin credentials? In web ui or in `common.properties`?
`parameters` is definitely not a good place to put those credentials, since it is a field to integrate with `Zeppelin Dynamic Form`.

2023-04-04 03:05 UTC, xiaomin0322 commented
@EricGao888  I expect to use the web UI to pass the parameters, and when I'm done, delete the parameters through zeppelinParamsMap.delete(). Is that OK with you?

2023-04-04 05:11 UTC, EricGao888 commented
> @EricGao888 I expect to use the web UI to pass the parameters, and when I'm done, delete the parameters through zeppelinParamsMap.delete(). Is that OK with you?

I think it is a good workaround to fill in the credentials in UI. You could refer to datasource center UI and try to mask the credentials in zeppelin task UI in the same way. Actually you don't need to call `zeppelinParamsMap.delete()` and it is fine if the credentials stay in memory as long as you don't print them in logging.

2023-04-11 09:15 UTC, xiaomin0322 commented
> > @EricGao888 I expect to use the web UI to pass the parameters, and when I'm done, delete the parameters through zeppelinParamsMap.delete(). Is that OK with you?
> 
> I think it is a good workaround to fill in the credentials in UI. You could refer to datasource center UI and try to mask the credentials in zeppelin task UI in the same way. Actually you don't need to call `zeppelinParamsMap.delete()` and it is fine if the credentials stay in memory as long as you don't print them in logging.

![image](https://user-images.githubusercontent.com/4092286/231113220-b9a95ccc-5478-4dc9-a4c8-d7f97db69ffb.png)

 already  use the web UI to pass the parameters, Please refer to the picture。

2023-04-13 03:21 UTC, EricGao888 reviewed
Please don't treat `password` as `pass word` and `username` as `user name`. BTW, please update related docs, both Chinese and English versions. Other LGTM.

2023-04-13 03:21 UTC, EricGao888 commented on dolphinscheduler-ui/src/locales/zh_CN/project.ts
> +    zeppelin_user_name: 'zeppelinUserName',
```suggestion
    zeppelin_username: 'zeppelinUsername',
```

2023-04-13 03:21 UTC, EricGao888 commented on dolphinscheduler-ui/src/locales/zh_CN/project.ts
> +    zeppelin_pass_word: 'zeppelinPassWord',
```suggestion
    zeppelin_password: 'zeppelinPassword',
```

2023-04-13 03:21 UTC, EricGao888 commented on dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinParameters.java
> +    private String userName;
```suggestion
    private String username;

```

2023-04-13 03:21 UTC, EricGao888 commented on dolphinscheduler-task-plugin/dolphinscheduler-task-zeppelin/src/main/java/org/apache/dolphinscheduler/plugin/task/zeppelin/ZeppelinParameters.java
> +    private String passWord;
```suggestion
    private String password;

```

2023-04-13 03:21 UTC, EricGao888 commented on dolphinscheduler-ui/src/locales/en_US/project.ts
> +    zeppelin_user_name: 'zeppelinUserName',
```suggestion
    zeppelin_username: 'zeppelinUsername',
```

2023-04-13 03:21 UTC, EricGao888 commented on dolphinscheduler-ui/src/locales/en_US/project.ts
> +    zeppelin_pass_word: 'zeppelinPassWord',
```suggestion
    zeppelin_password: 'zeppelinPassword',
```

2023-04-13 06:25 UTC, EricGao888 commented
> Please don't treat `password` as `pass word` and `username` as `user name`. BTW, please update related docs, both Chinese and English versions. Other LGTM.

There are still many such cases in this PR that I haven't marked, you need to fix them too : )

2023-04-13 08:24 UTC, xiaomin0322 commented
> > Please don't treat `password` as `pass word` and `username` as `user name`. BTW, please update related docs, both Chinese and English versions. Other LGTM.
> 
> There are still many such cases in this PR that I haven't marked, you need to fix them too : )

Modified relevant naming conventions and  related docs

2023-04-13 09:57 UTC, EricGao888 submitted a review, later dismissed
LGTM, waiting for CI to pass

2023-04-13 09:58 UTC, EricGao888 commented
> LGTM, waiting for CI to pass

@xiaomin0322 You need to run "mvn spotless:apply" to fix formatting errors.

2023-04-13 12:11 UTC, xiaomin0322 commented
> > LGTM, waiting for CI to pass
> 
> @xiaomin0322 You need to run "mvn spotless:apply" to fix formatting errors.

Executed

2023-04-14 02:09 UTC, EricGao888 approved these changes, later dismissed

2023-04-14 02:10 UTC, EricGao888 commented
> > > LGTM, waiting for CI to pass
> > 
> > 
> > @xiaomin0322 You need to run "mvn spotless:apply" to fix formatting errors.
> 
> Executed

@xiaomin0322 
![image](https://user-images.githubusercontent.com/34905992/231923821-d280bb1a-76fd-44fe-a0c7-c258d0368dc7.png)

Have u run it in ds root dir?

2023-04-14 02:44 UTC, xiaomin0322 commented
> > > > LGTM, waiting for CI to pass
> > > 
> > > 
> > > @xiaomin0322 You need to run "mvn spotless:apply" to fix formatting errors.
> > 
> > 
> > Executed
> 
> @xiaomin0322 ![image](https://user-images.githubusercontent.com/34905992/231923821-d280bb1a-76fd-44fe-a0c7-c258d0368dc7.png)
> 
> Have u run it in ds root dir?
 is run it in ds root dir, Strange, local testing passed.
![1681440087462](https://user-images.githubusercontent.com/4092286/231928065-d76122cd-5834-4e98-bd98-9aee6b1166c6.jpg)

2023-04-18 04:10 UTC, EricGao888 commented
> > > > > LGTM, waiting for CI to pass
> > > > 
> > > > 
> > > > @xiaomin0322 You need to run "mvn spotless:apply" to fix formatting errors.
> > > 
> > > 
> > > Executed
> > 
> > 
> > @xiaomin0322 ![image](https://user-images.githubusercontent.com/34905992/231923821-d280bb1a-76fd-44fe-a0c7-c258d0368dc7.png)
> > Have u run it in ds root dir?
> > is run it in ds root dir, Strange, local testing passed.
> > ![1681440087462](https://user-images.githubusercontent.com/4092286/231928065-d76122cd-5834-4e98-bd98-9aee6b1166c6.jpg)

That's wired. It works on my laptop and I've fixed it for u.

2023-04-18 04:11 UTC, EricGao888 approved these changes
LGTM if CI passes.

2023-04-18 04:18 UTC, merged

2023-04-18 06:19 UTC, EricGao888 commented
@xiaomin0322 Merged. Thanks for your contributions : )

2023-04-19 03:12 UTC, xiaomin0322 commented
> > > > > > LGTM, waiting for CI to pass
> > > > > 
> > > > > 
> > > > > @xiaomin0322 You need to run "mvn spotless:apply" to fix formatting errors.
> > > > 
> > > > 
> > > > Executed
> > > 
> > > 
> > > @xiaomin0322 ![image](https://user-images.githubusercontent.com/34905992/231923821-d280bb1a-76fd-44fe-a0c7-c258d0368dc7.png)
> > > Have u run it in ds root dir?
> > > is run it in ds root dir, Strange, local testing passed.
> > > ![1681440087462](https://user-images.githubusercontent.com/4092286/231928065-d76122cd-5834-4e98-bd98-9aee6b1166c6.jpg)
> 
> That's wired. It works on my laptop and I've fixed it for u.

ths