[Fix-14749][master] fix switch task  skip some task which should been…
apache/dolphinscheduler pull request #14750
Opened 2023-08-15 10:07 UTC by LiuShuangBJ

…  executed

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2023-08-26 11:09 UTC, caishunfeng commented
Hi @LiuShuangBJ Please link a issue, describe the problem you fixed and how to reproduce? thanks.

2023-08-27 03:19 UTC, LiuShuangBJ commented
已关联相关 issuse,在原issuse中有明确的复现步骤,以及代码级别的原因描述  @caishunfeng

2023-08-27 05:49 UTC, LiuShuangBJ commented
已添加相应的issue,在issue中有明确的触发条件



At 2023-08-26 19:09:28, "caishunfeng" ***@***.***> wrote:

Hi @LiuShuangBJ Please link a issue, describe the problem you fixed and how to reproduce? thanks.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-10-11 07:46 UTC, qingwli commented
Run 'mvn spotless:apply' to fix these violations.

2023-10-11 10:14 UTC, LiuShuangBJ commented
代码格式化已完成,请审阅

2023-10-11 10:32 UTC, fuchanghai commented
hi @LiuShuangBJ  it seem like similar to #14563  cc @caishunfeng

2023-10-12 02:31 UTC, fuchanghai commented
hi @LiuShuangBJ  1.在s1 之前加一个 s0 ，再次运行不符合预期
2.s1如果依赖一个延迟任务，当从s2 分支执行到s1 时，延时任务还未执行，不包含在compeleteTask 中，导致s1 也会跳过

2023-10-12 02:32 UTC, fuchanghai requested changes

2023-10-12 02:32 UTC, fuchanghai commented on dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java
> +            if (completeTaskList.containsKey(depNode)) {
hi @LiuShuangBJ 1.在s1 之前加一个 s0 ，再次运行不符合预期
2.s1如果依赖一个延迟任务，当从s2 分支执行到s1 时，延时任务还未执行，不包含在compeleteTask 中，导致s1 也会跳过

2023-10-12 04:44 UTC, LiuShuangBJ commented on dolphinscheduler-service/src/main/java/org/apache/dolphinscheduler/service/utils/DagHelper.java
> +            if (completeTaskList.containsKey(depNode)) {
yes ,and this problem had been closed by #14537, i will close this pr

2023-10-12 04:44 UTC, closed without merging