[Bug] [task definition] 修复任务定义修改,工作流无法生效问题
apache/dolphinscheduler pull request #14801
Opened 2023-08-24 02:44 UTC by sdhzwc

问题描述：所有版本都存在任务定义修改，但是在工作流当中无法生效问题，反之则可以。有如下几点：
1、修改无前置任务的任务定义，工作流当中不可用
2、修改有前置任务的任务定义，工作流当中不可用
3、切换工作流版本，修改任务定义，工作流当中不可用

动态演示修复前后对比：
一、修复前
![修改前](https://github.com/apache/dolphinscheduler/assets/46134044/dec605db-873b-4406-8da0-df2b3f41d970)

二、修复后
![修复后](https://github.com/apache/dolphinscheduler/assets/46134044/aff95911-e5b3-4e1e-8576-6872192137eb)

2023-08-24 06:51 UTC, EricGao888 commented
@sdhzwc Could u plz use English for PR descriptions?

2023-08-24 07:17 UTC, sdhzwc commented
> @sdhzwc Could u plz use English for PR descriptions?

Sorry, my English is not very good
Chinese is my native language, so describing it more smoothly

2023-08-24 07:50 UTC, ruanwenjun commented
> > @sdhzwc Could u plz use English for PR descriptions?
> 
> Sorry, my English is not very good Chinese is my native language, so describing it more smoothly

Thanks for your contribution, I changed the content to English.

2023-09-09 16:10 UTC, sdhzwc reviewed
I have completed the modifications

2023-10-12 06:53 UTC, qingwli commented
Please fix ut 

```
Error:  Failures: 
Error:    TaskDefinitionServiceImplTest.updateTaskDefinition:201 Expected org.apache.dolphinscheduler.api.exceptions.ServiceException to be thrown, but nothing was thrown.

2023-10-16 09:11 UTC, sdhzwc commented
#15036

2023-10-16 13:21 UTC, SbloodyS requested changes

2023-10-16 13:21 UTC, SbloodyS commented on dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
> +                                            post_task_code = #{taskCode}
The relationship between task and process can be one-to-many.

2023-10-16 13:21 UTC, SbloodyS commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
> +                int update_2 = processTaskRelationMapper.updateProcessTaskRelationTaskVersion(processTaskRelation);
```suggestion
                int updateProcessDefinitionVersionCount = processTaskRelationMapper.updateProcessTaskRelationTaskVersion(processTaskRelation);
```

2023-10-16 13:21 UTC, SbloodyS commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
> +            int update_3 = processDefinitionMapper.updateById(processDefinition);
```suggestion
            int updateProcessDefinitionCount = processDefinitionMapper.updateById(processDefinition);
```

2023-10-16 13:21 UTC, SbloodyS commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
> +            int insert_3 = processDefinitionLogMapper.insert(processDefinitionLog);
```suggestion
            int insertProcessDefinitionLogCount = processDefinitionLogMapper.insert(processDefinitionLog);
```

2023-10-17 04:01 UTC, sdhzwc commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
> +            int update_3 = processDefinitionMapper.updateById(processDefinition);
The modification has been completed

2023-10-17 04:01 UTC, sdhzwc commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
> +            int insert_3 = processDefinitionLogMapper.insert(processDefinitionLog);
The modification has been completed

2023-10-17 04:01 UTC, sdhzwc commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/TaskDefinitionServiceImpl.java
> +                int update_2 = processTaskRelationMapper.updateProcessTaskRelationTaskVersion(processTaskRelation);
The modification has been completed

2023-10-19 01:19 UTC, SbloodyS commented on dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
> +                                            post_task_code = #{taskCode}
BTW, `post_task_code` is not unique, `post_task_code` and `post_task_version` is unique.

2023-10-19 06:11 UTC, sdhzwc commented on dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessTaskRelationMapper.xml
> +                                            post_task_code = #{taskCode}
The modification has been completed

2023-10-24 14:22 UTC, SbloodyS approved these changes
LGTM

2023-10-25 08:42 UTC, davidzollo approved these changes
+1
LGTM

2023-10-25 12:25 UTC, merged