ces
apache/dolphinscheduler pull request #14937
Opened 2023-09-18 09:39 UTC by weyuhui110

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2023-09-18 09:55 UTC, weyuhui110 commented
PR 标题：解决 PostgreSQL 数组函数查询时 JSON 序列化错误的问题

PR 描述：
这个 PR 解决了在进行 PostgreSQL 数组函数查询时，由于缺少对数组对象的正确序列化支持，导致无法正常将查询结果转换为数组类型的 JSON 字符串而产生的错误。

主要修改内容：

添加对 PostgreSQL 数组类型数据的序列化支持。
修改 JSONUtils 类，使其能够正确处理 PostgreSQL 数组类型的数据。
解决这个问题的好处：

修复了在进行 PostgreSQL 数组函数查询时无法正确序列化结果的 bug，确保系统能够正常处理和使用数组类型的查询结果。
避免了因无法正确序列化 PostgreSQL 数组数据而导致的应用程序崩溃或异常。
特别注意事项：

请注意，在修改 JSONUtils 类时，只进行了必要的更改来添加对 PostgreSQL 数组的支持，并保持了现有的代码风格和结构。
在代码修改完成后，进行了相应的单元测试以确保修改不会影响现有功能的稳定性和正确性。
我已经在本地环境中测试了这些修改，并确保其能够成功解决报错问题。希望这个 PR 能够对项目有所贡献，请查看并审查我的修改。如果有任何疑问或建议，请随时提出，谢谢！

提醒：
在提交 PR 之前，请确保已经阅读并遵循该项目的贡献指南和代码风格规范，以确保你的修改符合项目的要求。

如果需要更详细的描述或其他帮助，请随时告诉我。祝你提交的 PR 成功被接受！

2023-09-18 09:55 UTC, weyuhui110 commented
PR 标题：解决 PostgreSQL 数组函数查询时 JSON 序列化错误的问题

PR 描述：
这个 PR 解决了在进行 PostgreSQL 数组函数查询时，由于缺少对数组对象的正确序列化支持，导致无法正常将查询结果转换为数组类型的 JSON 字符串而产生的错误。

主要修改内容：

添加对 PostgreSQL 数组类型数据的序列化支持。
修改 JSONUtils 类，使其能够正确处理 PostgreSQL 数组类型的数据。
解决这个问题的好处：

修复了在进行 PostgreSQL 数组函数查询时无法正确序列化结果的 bug，确保系统能够正常处理和使用数组类型的查询结果。
避免了因无法正确序列化 PostgreSQL 数组数据而导致的应用程序崩溃或异常。
特别注意事项：

请注意，在修改 JSONUtils 类时，只进行了必要的更改来添加对 PostgreSQL 数组的支持，并保持了现有的代码风格和结构。
在代码修改完成后，进行了相应的单元测试以确保修改不会影响现有功能的稳定性和正确性。
我已经在本地环境中测试了这些修改，并确保其能够成功解决报错问题。希望这个 PR 能够对项目有所贡献，请查看并审查我的修改。如果有任何疑问或建议，请随时提出，谢谢！

提醒：
在提交 PR 之前，请确保已经阅读并遵循该项目的贡献指南和代码风格规范，以确保你的修改符合项目的要求。

如果需要更详细的描述或其他帮助，请随时告诉我。祝你提交的 PR 成功被接受！

2023-09-19 15:26 UTC, ruanwenjun requested changes

2023-09-19 15:26 UTC, ruanwenjun commented on dolphinscheduler-common/pom.xml
> +        </dependency>
Don't put this in common module

2023-09-19 15:26 UTC, ruanwenjun commented on README.md
> +
```suggestion
```

2023-09-19 15:26 UTC, ruanwenjun commented on dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/JSONUtils.java
> +
Move this in SqlTask, please don't use Chinese in source code.

2023-09-19 15:29 UTC, ruanwenjun commented
Don't use Chinese in PR, otherwise I will close this PR. Please submit issue to describe this problem first, you can follow https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md

2023-11-08 06:58 UTC, SbloodyS commented
Closing due to inactive.

2023-11-08 06:58 UTC, closed without merging