[Feature][DataSource]Add flink datasource plugin
apache/dolphinscheduler pull request #15640
Opened 2024-02-27 06:22 UTC by pegasas

## Purpose of the pull request

https://github.com/apache/dolphinscheduler/issues/15630

[Feature][Datasource] add flink datasource

## Brief change log

Currently spark use thrift server for replacement of hiveserver2 to provide Spark SQL capability.
https://nightlies.apache.org/flink/flink-docs-master/docs/dev/table/sql-gateway/overview/
Flink SQL Gateway is also a replacement solution of hiveserver2.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-02-28 01:52 UTC, songjianet requested changes
![image](https://github.com/apache/dolphinscheduler/assets/19239641/9bfe572a-6979-4993-b3ec-c2e0388efe7e)

2024-02-28 18:03 UTC, pegasas commented on dolphinscheduler-datasource-plugin/dolphinscheduler-datasource-flink/src/main/java/org/apache/dolphinscheduler/plugin/datasource/flink/param/FlinkDataSourceProcessor.java
> +        flinkDataSourceParamDTO.setPort(Integer.parseInt(hostPortArray[0].split(Constants.COLON)[1]));
Ack.
Thanks for calling out.

2024-03-25 13:59 UTC, pegasas commented
Caused by: java.sql.SQLFeatureNotSupportedException: FlinkConnection#prepareStatement is not supported yet.
	at org.apache.flink.table.jdbc.BaseConnection.prepareStatement(BaseConnection.java:42)
	at org.apache.flink.table.jdbc.FlinkConnection.prepareStatement(FlinkConnection.java:49)
	at org.apache.dolphinscheduler.plugin.task.sql.SqlTask.prepareStatementAndBind(SqlTask.java:380)
	... 8 common frames omitted

will do some compacity work on sql task

2024-07-24 06:54 UTC, pegasas commented
> This pull request has been automatically marked as stale because it has not had recent activity for 120 days. It will be closed in 7 days if no further activity occurs.

remove stale

2024-11-29 00:28 UTC, closed without merging