[Bug] Fix can modify file which is not under resource path
apache/dolphinscheduler pull request #15652
Opened 2024-02-28 11:40 UTC by ruanwenjun

## Purpose of the pull request

Right now, user can use resource API to modify all files in the machine, this is not accepted.
This pr will fix this, user can only modify the resource file under resource path.

## Brief change log

- Add path restriction in the resource update path.
- Remove some unused code.

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-02-28 11:59 UTC, SbloodyS submitted a review, later dismissed
LGTM.

2024-02-28 13:48 UTC, songjianet requested changes
![image](https://github.com/apache/dolphinscheduler/assets/19239641/cb2a5a20-4e48-4654-b8ad-e8dcdfc981b1)
Please remove referenced but unused variables.

2024-02-29 08:42 UTC, rickchengx commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
> +    public Result<Object> uploadResource(User loginUser, String name, ResourceType type, MultipartFile file,
I am not sure how the user can only modify the resource file under resource path. Could you please give some brief description

2024-02-29 11:21 UTC, ruanwenjun commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ResourcesServiceImpl.java
> +    public Result<Object> uploadResource(User loginUser, String name, ResourceType type, MultipartFile file,
DS will throw exception when the user want to modify the system file which is not under resource path by update content API.  This can help to protect the system.

The upload API will not be affected.

2024-03-01 11:19 UTC, songjianet approved these changes

2024-03-01 11:38 UTC, caishunfeng approved these changes
LGTM overall

2024-03-01 11:39 UTC, merged