[Improvement-15603][API] When removing or modifying a workflow the system can check if there any tasks depend on it.
apache/dolphinscheduler pull request #15681
Opened 2024-03-07 07:39 UTC by calvinjiang

## Purpose of the pull request

This PR will close #15603 .

## Brief change log

## Verify this pull request
This change added tests and can be verified as follows:
- *Manually verified the change by testing locally.* 

The test results are as follows:

![image](https://github.com/apache/dolphinscheduler/assets/4928204/a884365d-a723-4dac-b28d-46596a1cf35a)
![image](https://github.com/apache/dolphinscheduler/assets/4928204/b252b8c7-16a1-4d8f-aee8-387a476a03ac)

![image](https://github.com/apache/dolphinscheduler/assets/4928204/ca9656de-19cc-466b-838f-e1b1be72e652)
![image](https://github.com/apache/dolphinscheduler/assets/4928204/658e5797-411d-43d9-a912-68e2619e9313)

![image](https://github.com/apache/dolphinscheduler/assets/4928204/89fdcb0b-9fff-4a0c-a9bc-700322575d24)

![image](https://github.com/apache/dolphinscheduler/assets/4928204/e7d61c3d-4d56-4fde-9e79-8de10183db5f)
![image](https://github.com/apache/dolphinscheduler/assets/4928204/f21d605c-82ab-4d4c-84c8-32b66d1dfc8d)

2024-03-07 11:35 UTC, zhuangchong commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/WorkFlowLineageController.java
> +        }
I recommend using `@ApiException` annotation for this part of the code.

2024-03-07 11:35 UTC, zhuangchong commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/impl/ProcessDefinitionServiceImpl.java
> +    private void checkIfDependentTaskExists(ProcessDefinition processDefinition) {
no called.

2024-03-07 11:35 UTC, zhuangchong commented on dolphinscheduler-ui/src/views/projects/workflow/components/dag/dag-context-menu.tsx
> +    // })
Please delete this part.

2024-03-08 00:36 UTC, songjianet requested changes
Please delete introduced but unused variables

2024-03-08 13:31 UTC, zhuangchong submitted a review, later dismissed
+1

2024-03-09 04:05 UTC, songjianet requested changes
![image](https://github.com/apache/dolphinscheduler/assets/19239641/24015044-62dd-49c3-8d9f-0c78d31c9e69)

2024-03-10 10:54 UTC, songjianet approved these changes

2024-03-10 10:55 UTC, merged

2024-03-11 09:42 UTC, qingwli commented
Looks like check https://github.com/apache/dolphinscheduler/actions/runs/8215624741/job/22469292085 not pass @calvinjiang  @songjianet

2024-03-11 13:40 UTC, SbloodyS commented
> Looks like check https://github.com/apache/dolphinscheduler/actions/runs/8215624741/job/22469292085 not pass @calvinjiang @songjianet

It's odd that `dolphinscheduler-api` module build passed...

2024-03-11 13:44 UTC, SbloodyS commented
Maybe the command `npm install pnpm@7 -g` install an incompatible version of `pnpm` in
https://github.com/apache/dolphinscheduler/blob/2395ba5ef84bdbce127edc36e6dd7e4f064ff0b1/.github/workflows/frontend.yml#L60-L64

PTAL @songjianet

2024-03-12 02:17 UTC, qingwli commented
Looks like some code format issue