fix dependent task logic
apache/dolphinscheduler pull request #15795
Opened 2024-04-02 13:16 UTC by abzymeinsjtu

2024-04-02 13:24 UTC, EricGao888 commented on dolphinscheduler-dao/src/main/resources/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapper.xml
> -        where process_definition_code=#{processDefinitionCode} and test_flag=#{testFlag}
Seems we need to keep the `test_flag=#{testFlag}` here. Other part LGTM

2024-04-02 14:04 UTC, EricGao888 submitted a review, later dismissed
LGTM, would u like to double check? @ruanwenjun @calvinjiang

2024-04-02 14:08 UTC, SbloodyS reviewed
Please link this pr to your issue and describe it.

2024-04-02 14:08 UTC, SbloodyS commented on dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
> +    /**L
Please remove unnessnary change.

2024-04-02 14:14 UTC, EricGao888 commented
> Please link this pr to your issue and describe it.

@SbloodyS This is a bug fix PR following up https://github.com/apache/dolphinscheduler/pull/15712/files

For details, see - https://github.com/apache/dolphinscheduler/issues/15707

However, in #15712, only one scenario - when instance triggered manually is fixed. This PR fix the scenario when the instance is triggered by scheduler or backfill.

2024-04-02 14:18 UTC, SbloodyS commented
> > Please link this pr to your issue and describe it.
> 
> @SbloodyS This is a bug fix PR following up https://github.com/apache/dolphinscheduler/pull/15712/files
> 
> For details, see - #15707
> 
> However, in #15712, only one scenario - when instance triggered manually is fixed. This PR fix the scenario when the instance is triggered by scheduler or backfill.

Ok. I got it.

2024-04-03 02:08 UTC, EricGao888 approved these changes, later dismissed

2024-04-03 02:10 UTC, SbloodyS requested changes

2024-04-03 02:10 UTC, SbloodyS commented on dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
> +    /**L
This still unaddressed.

2024-04-03 02:15 UTC, rickchengx commented on dolphinscheduler-dao/src/test/java/org/apache/dolphinscheduler/dao/mapper/ProcessInstanceMapperTest.java
> +    /**L
Overall LGTM, please delete this

2024-04-03 05:35 UTC, EricGao888 approved these changes

2024-04-03 05:38 UTC, SbloodyS approved these changes
+1

2024-04-03 05:50 UTC, ruanwenjun approved these changes
+1

2024-04-03 05:56 UTC, merged