[fix-15907] fix getTaskExitCode
apache/dolphinscheduler pull request #15911
Opened 2024-04-25 09:41 UTC by Zzih96

## Purpose of the pull request

fix https://github.com/apache/dolphinscheduler/issues/15907

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-04-25 13:18 UTC, ruanwenjun requested changes
Please directly use StringUtils

2024-04-25 13:18 UTC, ruanwenjun commented on dolphinscheduler-task-plugin/dolphinscheduler-task-remoteshell/src/main/java/org/apache/dolphinscheduler/plugin/task/remoteshell/RemoteExecutor.java
> +            String status = logLine.substring(startIndex, endIndex);
```suggestion
            String status = StringUtils.substringAfter(logLine, STATUS_TAG_MESSAGE);
```

2024-04-29 08:10 UTC, ruanwenjun approved these changes
LGTM

2024-05-09 03:00 UTC, rickchengx approved these changes
LGTM

2024-05-09 06:15 UTC, merged

2024-09-21 03:37 UTC, stoplyy commented
It seems a new bug has been introduced. 

The .trim() in the original code is necessary, otherwise the case of xxx-0\n cannot be handled.

![image](https://github.com/user-attachments/assets/1e2b357e-05da-49fe-a3f7-7fea2d292499)

2025-02-12 06:10 UTC, saowu commented
> It seems a new bug has been introduced.
> 
> The .trim() in the original code is necessary, otherwise the case of xxx-0\n cannot be handled.
> 
> ![image](https://private-user-images.githubusercontent.com/19727083/369592680-1e2b357e-05da-49fe-a3f7-7fea2d292499.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzNDA4NzksIm5iZiI6MTczOTM0MDU3OSwicGF0aCI6Ii8xOTcyNzA4My8zNjk1OTI2ODAtMWUyYjM1N2UtMDVkYS00OWZlLWEzZjctN2ZlYTJkMjkyNDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEyVDA2MDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjYzFhOTU1Y2RkMTFiMmM3MTA3OWU2ODU4YWZjNjBlMzdlOWE3ZmEwMGRhOGJiN2MyMTU0YjNiZWVhZjFkOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.izIoV2mHUUBaYJLA-a1feqbvtmpN2sDwD5-4Y1Cu044)

such is the case

2025-02-12 08:04 UTC, ruanwenjun commented
@stoplyy Should be fixed by #16296