Add RPC metrics
apache/dolphinscheduler pull request #16121
Opened 2024-06-06 08:14 UTC by ruanwenjun

## Purpose of the pull request

- Add RPC metrics
- Change default sync request timeout to 10s

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-06-06 09:12 UTC, SbloodyS requested changes

2024-06-06 09:12 UTC, SbloodyS commented on dolphinscheduler-extract/dolphinscheduler-extract-base/src/test/java/org/apache/dolphinscheduler/extract/base/metrics/RpcMetricsTest.java
> +        // 添加一个简单的内存中指标注册表
We should avoid chinese...

2024-06-06 10:41 UTC, rickchengx submitted a review, later dismissed
LGTM

2024-06-06 10:44 UTC, ruanwenjun commented on dolphinscheduler-extract/dolphinscheduler-extract-base/src/test/java/org/apache/dolphinscheduler/extract/base/metrics/RpcMetricsTest.java
> +        // 添加一个简单的内存中指标注册表
Done

2024-06-07 01:18 UTC, SbloodyS reviewed
CI did not passed.

2024-06-07 03:22 UTC, SbloodyS approved these changes, later dismissed
+1

2024-06-07 06:29 UTC, SbloodyS approved these changes

2024-06-11 02:55 UTC, rickchengx approved these changes
+1

2024-06-11 02:57 UTC, merged