[feature-15837] [api] Auto create workflow while import sql script
apache/dolphinscheduler pull request #16319
Opened 2024-07-15 10:44 UTC by eye-gu

## Purpose of the pull request

close #15837

2024-07-15 13:41 UTC, songjianet approved these changes, later dismissed

2024-07-16 06:16 UTC, SbloodyS requested changes
I think we don't need this feature. The scope of use of this feature is very small. I'm -1 on this.

2024-07-16 06:36 UTC, eye-gu commented
> I think we don't need this feature. The scope of use of this feature is very small. I'm -1 on this.

This feature is old and the function already exists. If it is no longer needed, should the relevant code be deleted because it is no longer available?

2024-08-02 07:43 UTC, SbloodyS commented
> This feature is old and the function already exists. If it is no longer needed, should the relevant code be deleted because it is no longer available?

You can create an issue first to call a vote for this. I'm +1 on this.

2024-12-12 00:28 UTC, closed without merging