[Fix-16331] fix the resource file cannot be displayed hierarchically
apache/dolphinscheduler pull request #16336
Opened 2024-07-17 07:24 UTC by JohnZp

## Purpose of the pull request

#16331 

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-07-17 07:47 UTC, SbloodyS requested changes

2024-07-17 07:47 UTC, SbloodyS commented on dolphinscheduler-alert/dolphinscheduler-alert-server/src/main/bin/start.sh
> +JVM_ARGS_ENV_FILE=${DOLPHINSCHEDULER_HOME}/bin/jvm_args_env.sh
Please avoid unnessnary change.

2024-07-17 14:03 UTC, Gallardot reviewed
LGTM, but please make the CI happy.
```
mvn spotless:apply
```

2024-07-18 01:17 UTC, JohnZp commented
> LGTM, but please make the CI happy.
> 
> ```
> mvn spotless:apply
> ```
Do I need to resubmit?

2024-07-18 01:23 UTC, SbloodyS commented
> Do I need to resubmit?

Yes

2024-07-20 01:30 UTC, ruanwenjun requested changes
We may have the same folder under different tenant. 
e.g. 
/dolphinscheduler/tenant1/resources/spark/xx.jar
/dolphinscheduler/tenant2/resources/spark/yy.jar

If we show the folder here, there may exist two spark directory here? this will cause confusion.

2024-09-05 02:50 UTC, SbloodyS commented
> e.g.
> /dolphinscheduler/tenant1/resources/spark/xx.jar
> /dolphinscheduler/tenant2/resources/spark/yy.jar

For this case, I think we can keep `tenant1/resources/spark/xx.jar` for user is enough.

Are you still working on this? @JohnZp

2024-11-15 04:13 UTC, closed without merging