[Chore] modify release doc
apache/dolphinscheduler pull request #16371
Opened 2024-07-25 07:33 UTC by wangxj3

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

(or)

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-07-25 07:39 UTC, SbloodyS requested changes

2024-07-25 07:39 UTC, SbloodyS commented on docs/docs/zh/contribute/release.md
> +其中1234ABCD5678EFGH9012IJKL3456MNOP7890QRST为公钥 ID。
Duplicated.

2024-07-25 07:45 UTC, SbloodyS approved these changes
LGTM

2024-07-26 01:30 UTC, caishunfeng approved these changes
LGTM

2024-07-26 01:30 UTC, merged