[Improvement][UI] use relative width for task editor
apache/dolphinscheduler pull request #16769
Opened 2024-11-05 06:44 UTC by kevinjmh

## Purpose of the pull request

This pull request update task editor style

## Brief change log

change from fixed width: 600px to 33%, the original one is too narrow to use

## Verify this pull request

This pull request is code cleanup without any test coverage.

## Pull Request Notice
[Pull Request Notice](https://github.com/apache/dolphinscheduler/blob/dev/docs/docs/en/contribute/join/pull-request.md)

If your pull request contain incompatible change, you should also add it to `docs/docs/en/guide/upgrede/incompatible.md`

2024-11-05 07:06 UTC, SbloodyS requested changes
This need to be discussion. You should create an discussion issue first.

2024-11-15 06:31 UTC, SbloodyS approved these changes
That's good! LGTM.

2024-11-16 08:51 UTC, zhongjiajie approved these changes

2024-11-16 08:51 UTC, zhongjiajie commented on dolphinscheduler-ui/src/components/modal/index.module.scss
> +  width: 33%;
NIT, why we use `33%` instead of others?

2024-11-16 10:22 UTC, Gallardot approved these changes

2024-11-16 10:22 UTC, merged