[Fix-4721][worker]The shell background starts the YARN task scenario, and the kill function is abnormal
apache/dolphinscheduler pull request #4722
Opened 2021-02-07 09:59 UTC by zhuangchong

## What is the purpose of the pull request
this closes #4721 
fix the shell background starts the YARN task scenario, and the kill function is abnormal

## Verify this pull request
This change added tests and can be verified as follows:
  - *Manually verified the change by testing locally.*

2021-02-11 01:59 UTC, CalvinKirs requested changes

2021-02-11 01:59 UTC, CalvinKirs commented on dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
> +
Please add comments for public methods.

2021-02-15 14:20 UTC, zhuangchong commented on dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/utils/StringUtils.java
> +
done.

2021-03-01 07:31 UTC, CalvinKirs approved these changes
LGTM

2021-03-11 14:46 UTC, CalvinKirs commented
please resolve conflicts.thx

2021-03-30 14:33 UTC, merged