[Fix-4137][Server]:TaskPriorityQueueConsumer no need to sleep for one second.
apache/dolphinscheduler pull request #4747
Opened 2021-02-09 03:24 UTC by AlleriaWindrunner

## *Tips*
- *Thanks very much for contributing to Apache DolphinScheduler.*
- *Please review https://dolphinscheduler.apache.org/en-us/community/index.html before opening a pull request.*

## What is the purpose of the pull request

*To improve the performance of scheduler.*

## Brief change log

*Because the default implements of queue is PriorityBlockingQueue, so there will be blocking in take() when has no task.*

## Verify this pull request

*(Please pick either of the following options)*

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

*The unit test is ok!*

This change added tests and can be verified as follows:

*(example:)*

  - *Added dolphinscheduler-dao tests for end-to-end.*
  - *Added CronUtilsTest to verify the change.*
  - *Manually verified the change by testing locally.*

2021-02-11 01:38 UTC, CalvinKirs commented
hi, there is time to synchronize the code, the dev code is updated.

2021-02-13 03:58 UTC, CalvinKirs reviewed
hi, thank you very much for your contribution, but this may not be the right approach, you can refer to #4140

2021-02-14 09:57 UTC, CalvinKirs requested changes

2021-02-14 09:57 UTC, CalvinKirs commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/consumer/TaskPriorityQueueConsumer.java
> -                        Thread.sleep(Constants.SLEEP_TIME_MILLIS);
See for specific reasons #4140

2021-02-17 04:28 UTC, AlleriaWindrunner commented
ok, i have analyzed three situations about this section code, and read the discussion in #4137.Considering that this is an internal scheduling system, I think you and GitFireMan's code are both fine. But I have a few suggestions for other users:
1. The default implementation is a generic version.
2. If you consider performance you can increase the worker node without having to optimize the code.
![image](https://user-images.githubusercontent.com/42635220/108156404-92730800-711b-11eb-9602-2525f0d4a6f0.png)

2021-02-17 04:41 UTC, AlleriaWindrunner commented
In addition, it is a good idea to split the main process and the code of the failure, if you have free time.>o<

2021-02-17 04:45 UTC, closed without merging