[1.3.6-prepare][FIX-#4617][LoggerServer] task log can not refresh in …
apache/dolphinscheduler pull request #5074
Opened 2021-03-17 05:51 UTC by CalvinKirs

…time #4618

issue #4617
pr #4618

2021-03-17 05:52 UTC, CalvinKirs commented
@597365581 please take a look.Thx

2021-03-17 06:31 UTC, 597365581 commented
.ok

2021-03-17 06:32 UTC, 597365581 commented
okokok

2021-03-23 05:27 UTC, lenboo approved these changes
+1

2021-03-30 15:02 UTC, chengshiwen requested changes

2021-03-30 15:02 UTC, chengshiwen commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
> +                logBuffer.add("welcome to use bigdata scheduling system...");
I think this line should be removed

2021-03-30 15:02 UTC, chengshiwen commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
>                          logBuffer.add(line);
The indent problem

2021-03-30 15:02 UTC, chengshiwen commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/AbstractCommandExecutor.java
> +
The empty line

2021-03-30 16:13 UTC, chengshiwen approved these changes
+1

2021-03-30 16:27 UTC, dailidong approved these changes
+1
good job

2021-03-30 16:28 UTC, merged