[Graduation] Modify the graduation version
apache/dolphinscheduler pull request #5177
Opened 2021-03-30 05:45 UTC by CalvinKirs

Remove DISCLAIMER
rename release package name

2021-03-30 15:07 UTC, chengshiwen requested changes
@CalvinKirs If you only search `incubat`, there will be a lot of relevant results

2021-03-30 15:10 UTC, CalvinKirs commented
> @CalvinKirs If you only search `incubat`, there will be a lot of relevant results



> @CalvinKirs If you only search `incubat`, there will be a lot of relevant results

I checked, not all of them need to be modified.

2021-03-30 15:20 UTC, chengshiwen requested changes

2021-03-30 15:20 UTC, chengshiwen commented on LICENSE
> +Apache DolphinScheduler  Subcomponents:
I have checked and there is no problem.
It would be better if one extra space could be removed.

2021-03-30 15:50 UTC, chengshiwen approved these changes
+1

2021-03-31 00:58 UTC, dailidong approved these changes
+1
good job

2021-03-31 00:58 UTC, merged