[Bug][worker] Fix sql task query result is empty (#5322)
apache/dolphinscheduler pull request #5324
Opened 2021-04-19 14:20 UTC by ruanwenjun

## Purpose of the pull request
close #5322

2021-04-20 07:00 UTC, chengshiwen requested changes, later dismissed

2021-04-20 07:00 UTC, chengshiwen commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
> +        String result = JSONUtils.toJsonString(resultJSONArray);
It is recommended to put these two lines in front of `if (sqlParameters.getSendEmail() == null || sqlParameters.getSendEmail()) {`, so `JSONUtils.toJsonString(resultJSONArray)` in `sendAttachment` can be replaced with `result`

2021-04-20 11:18 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/worker/task/sql/SqlTask.java
> +        String result = JSONUtils.toJsonString(resultJSONArray);
Good suggestion.

2021-04-21 03:04 UTC, chengshiwen commented
@ruanwenjun Hi, wenjun, is there a way to improve the unit test coverage?

2021-04-21 03:35 UTC, ruanwenjun commented
> @ruanwenjun Hi, wenjun, is there a way to improve the unit test coverage?

I suspect there is a problem with the unit test coverage statistics :smiley:

2021-04-21 10:03 UTC, ysrotciv reviewed
LGTM

2021-04-22 04:00 UTC, CalvinKirs approved these changes
LGTM

2021-04-22 04:01 UTC, CalvinKirs commented
> > @ruanwenjun Hi, wenjun, is there a way to improve the unit test coverage?
> 
> I suspect there is a problem with the unit test coverage statistics 😃

PowerMock nie wykrywa poprawnie pokrycia w przypadkach takich jak ten

2021-04-22 04:02 UTC, merged