[Feature-#5565][UI] Global Param passed by sense dependencies
apache/dolphinscheduler pull request #5628
Opened 2021-06-11 08:37 UTC by myangle1120

This pr will split the localParam and the globalParam,users could get the value of the localParams in the page of taskInstance

2021-06-11 17:19 UTC, CalvinKirs commented
Thanks for your contribution. @chengshiwen @zhuangchong hi, please take a  look,Thx

2021-06-16 09:59 UTC, zhuangchong requested changes

2021-06-16 09:59 UTC, zhuangchong commented on dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/udp/udp.vue
> +        // })
Please remove the comment code

2021-06-17 11:29 UTC, zhuangchong approved these changes
LGTM.

2021-06-17 13:08 UTC, JinyLeeChina reviewed
+1

2021-06-18 11:19 UTC, merged

2021-06-18 11:22 UTC, CalvinKirs commented
Deeply thanks for your contribution, this is a good beginning, considering that it's your first contribution, I think we can get deep communication, you can contact me through mail or add WeChat(Kris_Evil), when mail or added, please tell me who you are, I think I can help to familiar with the DolphinScheduler if you meet with problems.