[Improvement-5880][api] Optimized data structure of pagination query API results
apache/dolphinscheduler pull request #5882
Opened 2021-07-25 09:21 UTC by soreak

[5880][refactor]Optimized data structure of pagination query API results
- refactor PageInfo and delete returnDataListPaging in API
- modify the related Controller and Service and the corresponding Test

2021-07-25 15:39 UTC, CalvinKirs commented
thx for your contribution,ci check fail,you can refer this doc

2021-07-27 08:45 UTC, closed without merging

2021-07-27 09:24 UTC, zhuangchong requested changes

2021-07-27 09:24 UTC, zhuangchong commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/controller/AccessTokenController.java
> +            return error(result.getCode(),result.getMsg());
Return the result directly

2021-07-27 09:24 UTC, zhuangchong commented on dolphinscheduler-api/src/main/java/org/apache/dolphinscheduler/api/service/AccessTokenService.java
> +    PageInfo queryAccessTokenList(User loginUser, String searchVal, Integer pageNo, Integer pageSize);
Other interfaces return Result type, please keep the same