[Feature-#5273][server-master] Task node of SWITCH
apache/dolphinscheduler pull request #5922
Opened 2021-07-30 08:51 UTC by wangxj3

[Feature-#5273][server-master] Task node of SWITCH
Determine the nodes that need to be run based on the value of the parameter.

2021-07-30 11:58 UTC, Technoboy- requested changes, later dismissed

2021-07-30 11:58 UTC, Technoboy- commented on dolphinscheduler-common/src/main/java/org/apache/dolphinscheduler/common/enums/TaskType.java
> +    SWITCH(14, "SWITCH"),
Do here really compile with no errors ?

2021-08-13 01:56 UTC, JinyLeeChina reviewed
+1

2021-08-23 15:37 UTC, lenboo approved these changes
+1

2021-08-23 16:35 UTC, CalvinKirs approved these changes
LGTM

2021-08-23 16:35 UTC, merged