[Improvement-6540][server] Optimize the code related to the processInstanceExecMaps object
apache/dolphinscheduler pull request #6546
Opened 2021-10-15 08:55 UTC by eye-gu

## Purpose of the pull request

Optimize the code related to the processInstanceExecMaps object

## Brief change log

* add ProcessInstanceExecCacheManager
* change processInstanceExecMaps object related class

## Verify this pull request

  - *Added ProcessInstanceExecCacheManagerImplTest

2021-10-15 09:34 UTC, ruanwenjun requested changes
Just some minor changed.

2021-10-15 09:34 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/cache/impl/ProcessInstanceExecCacheManagerImpl.java
> +        return processInstanceExecMaps.values();
It's better to return an Immutable list here. If some modified the result, such remove or add, it will cause problem.
This method just return a view result, all change need by other interface.

2021-10-15 09:34 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/cache/impl/ProcessInstanceExecCacheManagerImpl.java
> +     * use a concurrent map cache
For code clean, remove this comment.

If you want to add a comment here, it's better to write why you use concurrent map here rather than just write use a concurrent map, we can easily know this is a concurrent map.

It's better to write what is the key of the map.

2021-10-15 09:34 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/registry/MasterRegistryClient.java
> +     * constructor
Remove this comment, we can know this is a constructor.

2021-10-15 09:34 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/EventExecuteService.java
> +     * constructor
Remove this comment, we can know this is a constructor.

2021-10-15 09:34 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/runner/EventExecuteService.java
> +
Remove extra empty line.

2021-10-15 09:34 UTC, ruanwenjun commented on dolphinscheduler-server/src/main/java/org/apache/dolphinscheduler/server/master/cache/ProcessInstanceExecCacheManager.java
> +    void cache(int processInstanceId, WorkflowExecuteThread workflowExecuteThread);
Do you want to use @Nonnull here? It seems if the workflowExecuteThread is null,  no exception thrown here.

So workflowExecuteThread is null is normal? If it's normal, it's better to tell other if the workflowExecuteThread is null, it will not be cached. The first time I saw notnull, I think it will throw an exception.

2021-10-16 01:27 UTC, ruanwenjun commented
Please fix the code style, you can import the checkstyle.xml file to your IDE.

2021-10-16 17:25 UTC, ououtt commented
sry about submitted multiple times, because I don't know checkstyle.
i do not change the failed unit test, how can i fixed it?

2021-10-17 04:54 UTC, ruanwenjun commented
@ououtt I am not sure if the UT failed is caused by your changes, you can rebase your code and submit again.

2021-10-18 02:47 UTC, ououtt commented
I found that I modified the constructor of the MasterRegistryClient class, it initialize the RegistryClient instance. Should I use an init method to initialize the MasterRegistryClient to make UT pass?

2021-10-18 05:45 UTC, ruanwenjun commented
@ououtt I think you can restore all the `init` method, your change shouldn't change the lifecycle of the components.

2021-10-18 05:59 UTC, closed without merging

2021-10-18 06:36 UTC, eye-gu commented
Thank you for your instruction. I deleted the original branch and resubmitted a new pr: 6556 .Maybe I can do better next time. @ruanwenjun